import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#f5f3f8" },
  safeDark: { backgroundColor: "#171321" },
  darkSurface: { backgroundColor: "#211b2b", borderBottomColor: "#382d43" },
  darkChatSurface: { backgroundColor: "#0d0d0f" },
  darkChatHeader: { backgroundColor: "#19191b", borderBottomColor: "#303034" },
  darkComposer: { backgroundColor: "#19191b", borderTopColor: "#303034" },
  darkComposerButton: { backgroundColor: "#303036" },
  darkComposerInput: { backgroundColor: "#262629", borderColor: "#3a3a3f" },
  darkInput: { backgroundColor: "#30243a", borderColor: "#493955" },
  darkText: { color: "#f7f2fa" },
  darkMuted: { color: "#b9adbf" },
  darkMessage: { backgroundColor: "#242426", borderColor: "#343438" },
  darkMineMessage: { backgroundColor: "#263b4d" },
  darkTheirMessageText: { color: "#f7f2fa" },
  darkTheirTime: { color: "#b9adbf" },
  darkTypingText: { color: "#b9adbf" },
  darkReplyTheirs: { color: "#b9adbf" },
  darkSearchResult: { color: "#b9adbf" },
  darkOptionText: { color: "#f7f2fa" },
  darkDialogTitle: { color: "#f7f2fa" },
  darkDialogMessage: { color: "#b9adbf" },
  darkEmptyText: { color: "#b9adbf" },
  darkNoteRow: { backgroundColor: "#211b2b", borderColor: "#493955" },
  darkCard: { backgroundColor: "#211b2b", borderColor: "#493955" },
  darkRow: { backgroundColor: "#211b2b", borderBottomColor: "#382d43" },
  appLayout: { flex: 1, flexDirection: "row", backgroundColor: "#16192a" },
  sidebarRail: { width: 72, backgroundColor: "#171a2b", alignItems: "center", paddingTop: 12, paddingBottom: 10 },
  railAvatar: { width: 50, height: 50, borderRadius: 25, backgroundColor: "#7562e9", justifyContent: "center", alignItems: "center", marginBottom: 22 },
  railAvatarText: { color: "#fff", fontSize: 22, fontWeight: "800" },
  railItems: { alignItems: "center", gap: 10 },
  railBottom: { flex: 1, justifyContent: "flex-end" },
  railButton: { width: 50, height: 50, borderRadius: 17, backgroundColor: "#24283a", justifyContent: "center", alignItems: "center" },
  railButtonActive: { backgroundColor: "#303449" },
  railIcon: { color: "#c4c8dc", fontSize: 25, fontWeight: "600" },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 28,
  },
  brandIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "#6f2da8",
    justifyContent: "center",
    alignItems: "center",
  },
  brandIconImage: { width: 42, height: 42, borderRadius: 14 },
  brandRowCompact: { gap: 7, marginBottom: 0 },
  navbarBrandIcon: { width: 30, height: 30, borderRadius: 9 },
  brandIconText: { color: "#fff", fontSize: 24 },
  brandText: { color: "#25173f", fontSize: 25, fontWeight: "800" },
  heading: {
    alignSelf: "stretch",
    color: "#171321",
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 8,
  },
  muted: { color: "#51485b", fontSize: 15, lineHeight: 22 },
  mutedSmall: { color: "#5d5367", fontSize: 13 },
  input: {
    alignSelf: "stretch",
    backgroundColor: "#fff",
    borderColor: "#e1dfea",
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 15,
    marginTop: 12,
  },
  primaryButton: {
    alignSelf: "stretch",
    backgroundColor: "#6f2da8",
    borderRadius: 12,
    minHeight: 54,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 18,
  },
  primaryButtonText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  disabled: { opacity: 0.45 },
  error: {
    alignSelf: "stretch",
    color: "#c62828",
    fontSize: 13,
    marginTop: 10,
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 10,
    borderBottomColor: "#e8e5ef",
    borderBottomWidth: 1,
    backgroundColor: "#fff",
  },
  listHeaderCopy: { flex: 1, marginLeft: 8 },
  headerActions: { marginLeft: "auto", flexDirection: "row", alignItems: "center", gap: 14 },
  navbarBrandText: { color: "#25173f", fontSize: 21, fontWeight: "800", marginRight: 10 },
  headerProfileButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#eadcf5", justifyContent: "center", alignItems: "center" },
  headerProfileText: { color: "#6f2da8", fontSize: 18, fontWeight: "800" },
  headerIconButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: "#f1e8f7", justifyContent: "center", alignItems: "center" },
  menuButton: { paddingRight: 8, paddingVertical: 5 },
  listSearchRow: { flexDirection: "row", alignItems: "center", gap: 10, marginHorizontal: 14, marginTop: 12, marginBottom: 10, minHeight: 52 },
  conversationSearchField: { flex: 1, flexDirection: "row", alignItems: "center", gap: 10, minHeight: 52, paddingHorizontal: 15, backgroundColor: "#fff", borderWidth: 1, borderColor: "#d9d0e1", borderRadius: 16 },
  conversationTabs: { flexDirection: "row", marginHorizontal: 10, marginBottom: 8, padding: 4, borderRadius: 14, backgroundColor: "#f4f1f8" },
  conversationTab: { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7, minHeight: 46, borderRadius: 12, paddingHorizontal: 6 },
  conversationTabActive: { backgroundColor: "#fff", elevation: 2, shadowColor: "#24132f", shadowOpacity: 0.08, shadowRadius: 4, shadowOffset: { width: 0, height: 1 } },
  darkConversationTabActive: { backgroundColor: "#3a2b47", shadowOpacity: 0 },
  conversationTabText: { color: "#777184", fontSize: 12, fontWeight: "700" },
  conversationTabTextActive: { color: "#6f2da8" },
  conversationTabCount: { minWidth: 20, height: 20, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: "#e8e1ed" },
  conversationTabCountActive: { backgroundColor: "#eadcf5" },
  conversationTabCountText: { color: "#777184", fontSize: 10, fontWeight: "800" },
  conversationTabCountTextActive: { color: "#6f2da8" },
  listSearchInput: { flex: 1, paddingVertical: 9, fontSize: 14 },
  bottomNavbar: { flexDirection: "row", justifyContent: "space-around", alignItems: "center", paddingTop: 8, paddingBottom: Platform.OS === "ios" ? 18 : 8, backgroundColor: "#fff", borderTopWidth: 1, borderTopColor: "#e8e5ef" },
  bottomNavItem: { flex: 1, minWidth: 0, alignItems: "center", gap: 3, paddingVertical: 7, minHeight: 58 },
  bottomNavActive: { borderRadius: 12, backgroundColor: "#f2eafa" },
  newChatFab: { position: "absolute", right: 20, bottom: Platform.OS === "ios" ? 122 : 108, width: 58, height: 58, borderRadius: 18, backgroundColor: "#6f2da8", alignItems: "center", justifyContent: "center", elevation: 7, shadowColor: "#301542", shadowOpacity: 0.28, shadowRadius: 8, shadowOffset: { width: 0, height: 4 }, zIndex: 10 },
  bottomProfileBubble: { width: 27, height: 27, borderRadius: 14, backgroundColor: "#eadcf5", alignItems: "center", justifyContent: "center" },
  bottomProfileText: { color: "#6f2da8", fontSize: 12, fontWeight: "800" },
  bottomNavLabel: { color: "#51485b", fontSize: 12, fontWeight: "700" },
  darkBottomNavLabel: { color: "#b9adbf" },
  bottomNavLabelActive: { color: "#6f2da8", fontSize: 12, fontWeight: "800" },
  menuText: { color: "#6f2da8", fontSize: 23, fontWeight: "700" },
  listTitle: { color: "#171321", fontSize: 20, fontWeight: "800" },
  actionText: { color: "#5b218e", fontSize: 14, fontWeight: "800" },
  listContent: { padding: 12 },
  emptyContent: { flexGrow: 1, justifyContent: "center", alignItems: "center" },
  conversationRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 15,
    borderRadius: 16,
    marginBottom: 7,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#eee9f2",
    elevation: 1,
  },
  callHistoryRow: { flexDirection: "row", alignItems: "center", padding: 14, backgroundColor: "#fff", borderBottomWidth: 1, borderBottomColor: "#eeeaf3" },
  callMissed: { color: "#c62828" },
  mediaGridItem: { width: "47%", margin: "1.5%", padding: 10, borderRadius: 12, backgroundColor: "#fff", minHeight: 150 },
  globalMediaImage: { width: "100%", height: 105, borderRadius: 9, marginBottom: 7 },
  mediaItemName: { color: "#211b2b", fontSize: 13, fontWeight: "700" },
  noteEditor: { margin: 14, padding: 18, backgroundColor: "#fff", borderRadius: 18, borderWidth: 1, borderColor: "#eee8f3", shadowColor: "#301542", shadowOpacity: 0.06, shadowRadius: 10, elevation: 2 },
  noteEditorHeading: { color: "#211b2b", fontSize: 14, fontWeight: "800", marginBottom: 10 },
  noteTitleInput: { color: "#211b2b", fontSize: 18, fontWeight: "700", paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: "#eee8f3" },
  noteBodyInput: { color: "#463c4d", fontSize: 14, lineHeight: 20, minHeight: 74, paddingVertical: 12 },
  reminderInputRow: { flexDirection: "row", alignItems: "center", backgroundColor: "#f8f5fa", borderRadius: 10, paddingHorizontal: 10, marginBottom: 14 },
  reminderIcon: { color: "#6f2da8", fontSize: 20 },
  reminderInput: { flex: 1, color: "#463c4d", fontSize: 13, paddingVertical: 10, paddingHorizontal: 8 },
  noteButtons: { flexDirection: "row", justifyContent: "flex-end", alignItems: "center", gap: 12 },
  noteCancelButton: { paddingHorizontal: 10, paddingVertical: 10 },
  noteSaveButton: { backgroundColor: "#6f2da8", borderRadius: 10, paddingHorizontal: 16, paddingVertical: 10 },
  notesList: { paddingHorizontal: 14, paddingBottom: 24 },
  notesEmptyList: { flexGrow: 1, padding: 14 },
  notesEmpty: { flex: 1, justifyContent: "center", alignItems: "center", padding: 28 },
  notesEmptyIcon: { color: "#bda8cb", fontSize: 38, marginBottom: 8 },
  notesEmptyTitle: { color: "#211b2b", fontSize: 16, fontWeight: "800", marginBottom: 4 },
  noteRow: { flexDirection: "row", alignItems: "stretch", marginBottom: 10, borderRadius: 15, backgroundColor: "#fff", overflow: "hidden", borderWidth: 1, borderColor: "#eee8f3", elevation: 1 },
  noteAccent: { width: 5, backgroundColor: "#9b63bd" },
  noteContent: { flex: 1, padding: 14, minWidth: 0 },
  noteTitle: { color: "#211b2b", fontSize: 15, fontWeight: "800", marginBottom: 5 },
  noteBody: { color: "#6f6677", fontSize: 13, lineHeight: 18 },
  noteActions: { justifyContent: "space-between", alignItems: "flex-end", padding: 14, paddingLeft: 4 },
  reminderBadge: { alignSelf: "flex-start", marginTop: 10, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, backgroundColor: "#f1e8f7" },
  reminderBadgeText: { color: "#6f2da8", fontSize: 11, fontWeight: "700" },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#eadcf5",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarSmall: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#eadcf5",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: "#6f2da8", fontWeight: "800", fontSize: 16 },
  presenceDot: { position: "absolute", right: 0, bottom: 0, width: 13, height: 13, borderRadius: 7, borderWidth: 2, borderColor: "#fff" },
  darkPresenceDot: { borderColor: "#211b2b" },
  presenceOnline: { backgroundColor: "#2e9d55" },
  presenceAway: { backgroundColor: "#ed9b2f" },
  presenceBusy: { backgroundColor: "#d94a4a" },
  presenceOffline: { backgroundColor: "#9b95a5" },
  conversationCopy: { flex: 1, marginLeft: 12 },
  conversationTitle: {
    color: "#211b2b",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 4,
  },
  badge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#6f2da8",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 6,
  },
  badgeText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  chatContainer: { flex: 1 },
  chatHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderBottomColor: "#e8e5ef",
    borderBottomWidth: 1,
  },
  backButton: { paddingRight: 10, paddingVertical: 3 },
  backText: { color: "#6f2da8", fontSize: 38, lineHeight: 32 },
  chatHeaderCopy: { flex: 1, marginLeft: 10 },
  callActions: { flexDirection: "row", gap: 12, alignItems: "center" },
  callText: { color: "#6f2da8", fontSize: 22, fontWeight: "700" },
  messageSearchRow: { paddingHorizontal: 10, paddingTop: 8, paddingBottom: 4, backgroundColor: "#fff" },
  messageSearchBox: { flexDirection: "row", alignItems: "center", minHeight: 46, paddingHorizontal: 12, backgroundColor: "#f4f1f8", borderRadius: 14, borderWidth: 1, borderColor: "#e3dce9" },
  messageSearchInput: { flex: 1, paddingHorizontal: 9, paddingVertical: 8, fontSize: 15 },
  searchResultText: { color: "#6f6677", fontSize: 12, fontWeight: "700", paddingHorizontal: 5, paddingTop: 5 },
  chatTitle: {
    color: "#211b2b",
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 2,
  },
  messageList: { flexGrow: 1, paddingHorizontal: 14, paddingTop: 12, paddingBottom: 10, justifyContent: "flex-end" },
  messageBubble: {
    maxWidth: "82%",
    paddingHorizontal: 13,
    paddingVertical: 9,
    borderRadius: 19,
    marginBottom: 7,
  },
  myMessage: {
    alignSelf: "flex-end",
    backgroundColor: "#6f2da8",
    borderBottomRightRadius: 4,
  },
  theirMessage: {
    alignSelf: "flex-start",
    backgroundColor: "#fff",
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: "#e4e0eb",
  },
  myMessageText: { color: "#fff", fontSize: 16, lineHeight: 22 },
  theirMessageText: { color: "#17121d", fontSize: 16, lineHeight: 22 },
  myTime: { color: "#e6d9f0", fontSize: 10, marginTop: 4, textAlign: "right" },
  theirTime: {
    color: "#908898",
    fontSize: 10,
    marginTop: 4,
    textAlign: "right",
  },
  errorInline: {
    color: "#c62828",
    fontSize: 12,
    paddingHorizontal: 12,
    paddingBottom: 5,
  },
  typingIndicator: { flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 16, paddingVertical: 7 },
  typingDots: { flexDirection: "row", alignItems: "center", gap: 3, paddingHorizontal: 8, paddingVertical: 6, borderRadius: 12, backgroundColor: "#242426" },
  typingDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: "#aaa2b3" },
  typingText: { color: "#6f6677", fontSize: 12, fontStyle: "italic" },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#e8e5ef",
  },
  modalCloseButton: { paddingHorizontal: 6, paddingVertical: 6 },
  scheduleTitleRow: { flexDirection: "row", alignItems: "center", gap: 10, flex: 1 },
  scheduleIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: "#6f2da8", alignItems: "center", justifyContent: "center" },
  scheduleForm: { flex: 1, padding: 18, backgroundColor: "#fff" },
  scheduleFormContent: { paddingBottom: 28 },
  schedulePeople: { gap: 8, marginTop: 4 },
  schedulePersonSearch: { flexDirection: "row", alignItems: "center", gap: 8, minHeight: 46, paddingHorizontal: 12, marginBottom: 8, backgroundColor: "#f8f5fa", borderWidth: 1, borderColor: "#e8dff0", borderRadius: 12 },
  schedulePersonSearchInput: { flex: 1, paddingVertical: 8, fontSize: 15 },
  schedulePerson: { flexDirection: "row", alignItems: "center", gap: 10, minHeight: 52, padding: 8, borderRadius: 13, backgroundColor: "#f8f5fa", borderWidth: 1, borderColor: "#eee8f3" },
  schedulePersonActive: { borderColor: "#6f2da8", backgroundColor: "#f1e8f7" },
  schedulePersonAvatar: { width: 34, height: 34, borderRadius: 17, alignItems: "center", justifyContent: "center", backgroundColor: "#eadcf5" },
  scheduleLabel: { color: "#6f2da8", fontSize: 12, fontWeight: "800", marginTop: 12, marginBottom: 2 },
  adminHeaderTitle: { flexDirection: "row", alignItems: "center", gap: 10 },
  adminStats: { flexDirection: "row", gap: 8, padding: 14 },
  adminStat: { flex: 1, backgroundColor: "#fff", borderRadius: 14, padding: 12, borderWidth: 1, borderColor: "#eee8f3" },
  adminStatValue: { color: "#6f2da8", fontSize: 22, fontWeight: "800" },
  adminStatLabel: { color: "#888294", fontSize: 11, marginTop: 3 },
  adminSearch: { flexDirection: "row", alignItems: "center", marginHorizontal: 14, marginBottom: 4, paddingHorizontal: 12, backgroundColor: "#f4f1f8", borderRadius: 12 },
  adminSearchInput: { flex: 1, paddingVertical: 10, paddingHorizontal: 8, fontSize: 14 },
  adminError: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 14, paddingVertical: 8 },
  adminUserRow: { flexDirection: "row", alignItems: "center", padding: 13, marginBottom: 8, borderRadius: 14, backgroundColor: "#fff", borderWidth: 1, borderColor: "#eee8f3" },
  adminUserAvatar: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#eadcf5", justifyContent: "center", alignItems: "center", marginRight: 10 },
  roleBadge: { backgroundColor: "#f1e8f7", borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5 },
  roleBadgeText: { color: "#6f2da8", fontSize: 10, fontWeight: "800" },
  adminTabs: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#eee8f3", marginBottom: 6 },
  adminTab: { flex: 1, alignItems: "center", paddingVertical: 12 },
  adminTabActive: { borderBottomWidth: 2, borderBottomColor: "#6f2da8" },
  adminTabText: { color: "#888294", fontSize: 12, fontWeight: "700" },
  adminTabTextActive: { color: "#6f2da8" },
  adminStatus: { color: "#888294", fontSize: 11, marginTop: 3, textTransform: "capitalize" },
  adminRestrictText: { color: "#c62828", fontSize: 12, fontWeight: "700" },
  adminRowActions: { alignItems: "flex-end", gap: 10 },
  adminForm: { padding: 18, gap: 10 },
  adminSectionTitle: { color: "#211b2b", fontSize: 18, fontWeight: "800", marginBottom: 4 },
  adminFormInput: { backgroundColor: "#f8f5fa", borderWidth: 1, borderColor: "#e8dff0", borderRadius: 12, paddingHorizontal: 13, paddingVertical: 12, color: "#211b2b", fontSize: 14, marginTop: 2 },
  adminFieldLabel: { color: "#6f2da8", fontSize: 11, fontWeight: "800", letterSpacing: 0.6, marginTop: 10, marginBottom: 2, textTransform: "uppercase" },
  adminRoleRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 8 },
  adminBulk: { alignItems: "center", padding: 28, gap: 12 },
  adminDetailCard: { width: "94%", maxHeight: "90%", backgroundColor: "#fff", borderRadius: 24, padding: 22, elevation: 12, shadowColor: "#24132f", shadowOpacity: 0.18, shadowRadius: 18, shadowOffset: { width: 0, height: 8 } },
  adminDetailLine: { color: "#888294", fontSize: 13, marginTop: 5, marginBottom: 8 },
  adminNotice: { marginHorizontal: 14, marginBottom: 6, padding: 10, borderRadius: 10, backgroundColor: "#e7f5ed" },
  adminNoticeText: { color: "#216e3a", fontSize: 12, fontWeight: "700" },
  modalTools: { padding: 14, backgroundColor: "#fff" },
  searchInput: {
    backgroundColor: "#f4f1f8",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 15,
    marginBottom: 10,
  },
  modeRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  userRow: { flexDirection: "row", alignItems: "center", padding: 13, borderBottomWidth: 1, borderBottomColor: "#eeeaf3" },
  emptyText: { textAlign: "center", color: "#777184", padding: 24 },
  profileCard: { alignItems: "center", backgroundColor: "#fff", padding: 24, marginBottom: 18 },
  profileAvatar: { width: 82, height: 82, borderRadius: 28, backgroundColor: "#eadcf5", justifyContent: "center", alignItems: "center", marginBottom: 12 },
  profileAvatarText: { color: "#6f2da8", fontSize: 32, fontWeight: "800" },
  profileAvatarImage: { width: "100%", height: "100%", borderRadius: 28 },
  profileNameInput: { minWidth: 210, color: "#211b2b", fontSize: 20, fontWeight: "800", textAlign: "center", borderBottomWidth: 1, borderBottomColor: "#ddd5e8", paddingVertical: 5 },
  saveProfileButton: { backgroundColor: "#6f2da8", borderRadius: 18, paddingHorizontal: 16, paddingVertical: 9, marginTop: 12 },
  saveProfileText: { color: "#fff", fontSize: 12, fontWeight: "700" },
  profileName: { color: "#211b2b", fontSize: 21, fontWeight: "800", marginBottom: 4 },
  statusHeading: { alignSelf: "stretch", color: "#211b2b", fontSize: 15, fontWeight: "700", marginTop: 24, marginBottom: 10 },
  statusOptions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statusOption: { borderWidth: 1, borderColor: "#ddd5e8", borderRadius: 18, paddingHorizontal: 13, paddingVertical: 8 },
  statusOptionActive: { backgroundColor: "#6f2da8", borderColor: "#6f2da8" },
  statusOptionText: { color: "#6f2da8", fontSize: 12, fontWeight: "600" },
  statusOptionTextActive: { color: "#fff", fontSize: 12, fontWeight: "700" },
  settingRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", backgroundColor: "#fff", paddingHorizontal: 18, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "#eeeaf3" },
  settingLabel: { color: "#2b2335", fontSize: 15, fontWeight: "600" },
  settingsLogoutButton: { margin: 18, borderRadius: 12, borderWidth: 1, borderColor: "#efb3b3", paddingVertical: 13, alignItems: "center" },
  settingsLogoutText: { color: "#c62828", fontSize: 15, fontWeight: "700" },
  testNotificationButton: { alignSelf: "center", marginTop: 18, paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10, backgroundColor: "#f1e8f7" },
  drawerBackdrop: { flex: 1, flexDirection: "row", backgroundColor: "rgba(20,16,30,0.42)" },
  drawer: { width: "82%", maxWidth: 360, backgroundColor: "#f8f9fd", elevation: 12, shadowColor: "#000", shadowOpacity: 0.2, shadowRadius: 12 },
  drawerSafe: { flex: 1 },
  drawerHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, backgroundColor: "#fff" },
  drawerAction: { paddingHorizontal: 18, paddingVertical: 16, backgroundColor: "#fff", borderBottomWidth: 1, borderBottomColor: "#eeeaf3" },
  drawerActionText: { color: "#2b2335", fontSize: 15, fontWeight: "600" },
  logoutText: { color: "#c62828", fontSize: 15, fontWeight: "700" },
  drawerDivider: { height: 16 },
  drawerCloseArea: { flex: 1 },
  pinnedLabel: { color: "#f59e0b", fontSize: 10, fontWeight: "700", marginBottom: 3 },
  replyMine: { color: "#e6d9f0", fontSize: 11, marginBottom: 4 },
  replyTheirs: { color: "#777184", fontSize: 11, marginBottom: 4 },
  reactionMine: { color: "#fff", fontSize: 13, marginTop: 4 },
  reactionTheirs: { color: "#6f2da8", fontSize: 13, marginTop: 4 },
  modalBackdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(25, 18, 35, 0.38)" },
  optionsSheet: { backgroundColor: "#fff", borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 18, paddingBottom: 28, maxHeight: "82%" },
  actionSheet: { backgroundColor: "#fff", borderTopLeftRadius: 22, borderTopRightRadius: 22, paddingHorizontal: 18, paddingTop: 10, paddingBottom: 28 },
  actionSheetHandle: { alignSelf: "center", width: 42, height: 4, borderRadius: 3, backgroundColor: "#d7d0df", marginBottom: 12 },
  actionSheetTitle: { color: "#211b2b", fontSize: 17, fontWeight: "800", marginBottom: 12 },
  reactionStrip: { flexDirection: "row", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "#eeeaf3", paddingBottom: 12, marginBottom: 5 },
  reactionButton: { width: 38, height: 38, borderRadius: 19, backgroundColor: "#f4f1f8", alignItems: "center", justifyContent: "center" },
  reactionEmoji: { fontSize: 20 },
  actionSheetRow: { flexDirection: "row", alignItems: "center", gap: 14, paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: "#f0edf4" },
  infoCard: { margin: 24, backgroundColor: "#fff", borderRadius: 18, padding: 20, elevation: 8 },
  infoLabel: { color: "#888294", fontSize: 12, marginTop: 14 },
  infoValue: { color: "#211b2b", fontSize: 14, marginTop: 3 },
  optionRow: { flexDirection: "row", alignItems: "center", gap: 14, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "#f0edf4" },
  optionText: { color: "#2b2335", fontSize: 14, fontWeight: "600" },
  optionDangerText: { color: "#c62828", fontSize: 14, fontWeight: "600" },
  optionCancel: { alignItems: "center", paddingTop: 16 },
  callOverlay: { flex: 1, justifyContent: "center", alignItems: "center", backgroundColor: "rgba(25, 18, 35, 0.55)" },
  callCard: { width: "86%", backgroundColor: "#fff", borderRadius: 22, padding: 24, alignItems: "center", elevation: 10 },
  callTitle: { color: "#211b2b", fontSize: 19, fontWeight: "800", marginTop: 10 },
  callNotice: { color: "#777184", fontSize: 12, lineHeight: 18, textAlign: "center", marginVertical: 16 },
  callButtons: { flexDirection: "row", gap: 12, marginTop: 20 },
  callAccept: { backgroundColor: "#2e7d32", borderRadius: 20, paddingHorizontal: 20, paddingVertical: 11 },
  callDecline: { backgroundColor: "#c62828", borderRadius: 20, paddingHorizontal: 20, paddingVertical: 11, marginTop: 16 },
  callButtonText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  dialogOverlay: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24, backgroundColor: "rgba(25, 18, 35, 0.45)" },
  dialogCard: { width: "100%", maxWidth: 380, backgroundColor: "#fff", borderRadius: 18, padding: 20, elevation: 10 },
  dialogTitle: { color: "#211b2b", fontSize: 18, fontWeight: "800", marginBottom: 8 },
  dialogMessage: { color: "#777184", fontSize: 14, lineHeight: 20 },
  dialogButtons: { flexDirection: "row", justifyContent: "flex-end", flexWrap: "wrap", gap: 8, marginTop: 18 },
  dialogButton: { borderRadius: 10, backgroundColor: "#f0e8f7", paddingHorizontal: 14, paddingVertical: 10 },
  dialogDangerButton: { backgroundColor: "#fdecec" },
  dialogButtonText: { color: "#6f2da8", fontSize: 13, fontWeight: "700" },
  dialogDangerText: { color: "#c62828" },
  attachmentImage: { width: 220, height: 150, borderRadius: 10, marginBottom: 6 },
  attachmentFile: { flexDirection: "row", alignItems: "center", gap: 7, paddingVertical: 3 },
  replyBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingHorizontal: 12, paddingVertical: 8, backgroundColor: "#f4f1f8" },
  attachButton: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#f0eaf5", justifyContent: "center", alignItems: "center" },
  composerEmojiButton: { width: 38, height: 42, alignItems: "center", justifyContent: "center" },
  attachText: { color: "#6f2da8", fontSize: 23, lineHeight: 25 },
  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 7,
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: Platform.OS === "ios" ? 18 : 10,
    backgroundColor: "#fff",
    borderTopColor: "#e8e5ef",
    borderTopWidth: 1,
    shadowColor: "#24132f",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  composerInput: {
    flex: 1,
    maxHeight: 110,
    backgroundColor: "#f4f1f8",
    borderWidth: 1,
    borderColor: "#ded4e6",
    borderRadius: 23,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
  },
  sendButton: {
    backgroundColor: "#6f2da8",
    minHeight: 48,
    width: 48,
    paddingHorizontal: 0,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    minWidth: 48,
  },
  sendButtonText: { display: "none" },
});
